server:
  application:
    name: config-center
  port: 8888
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/forezp/SpringcloudConfig/
          # 指定搜索路径，如果有多个路径则使用,分隔
          searchPaths: respo
          username: kanghongjie
          password: Kjie55226312
          # 对于使用git,svn做为后端配置，从远程库获取配置文件，需要存储到本地文件
          basedir: /tmp/spring-cloud-repo
          # 配置中心通过git从远程git库，有时本地的拷贝被污染，这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          force-pull: true
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#spring.cloud.config.label：配置仓库的分支
#spring.cloud.config.server.git.username：访问git仓库的用户名
#spring.cloud.config.server.git.password：访问git仓库的用户密码